{
  "data":
  {
    "repository":
    {
      "issue":
      {
        "number": 287,
        "title": "[BUG] Installation issue: `const PyCall = Base.require`",
        "body": "**Describe the bug**\r\nI am using Python installed in a spack environment and want to use PySR (the following works with the system-python). So I installed Julia, added it to my `PATH` and then I do the installation instructions, which fail:\r\n```\r\n>>> import pysr\r\n>>> pysr.install()\r\n[ Info: Julia version info\r\nJulia Version 1.8.5\r\n< all the diagnostics >\r\n┌ Info: PyCall is already installed and compatible with Python executable.\r\n│ \r\n│ PyCall:\r\n│     python: /software_modules/spack/var/spack/environments/ml-23-03/.spack-env/view/bin/python\r\n│     libpython: /software_modules/spack/opt/spack/linux-fedora36-zen/gcc-8.5.0/python-3.10.10-ldbbqz6242q36jrznozylpqzburhgu2v/lib/libpython3.10.so.1.0\r\n│ Python:\r\n│     python: /software_modules/spack/var/spack/environments/ml-23-03/.spack-env/view/bin/python\r\n└     libpython: /software_modules/spack/opt/spack/linux-fedora36-zen/gcc-8.5.0/python-3.10.10-ldbbqz6242q36jrznozylpqzburhgu2v/lib/libpython3.10.so.1.0\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/.local/lib/python3.10/site-packages/pysr/julia_helpers.py\", line 85, in install\r\n    Main, init_log = init_julia(julia_project, quiet=quiet, return_aux=True)\r\n  File \"/home/.local/lib/python3.10/site-packages/pysr/julia_helpers.py\", line 192, in init_julia\r\n    Julia(**julia_kwargs)\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 519, in __init__\r\n    self._call(\"const PyCall = Base.require({0})\".format(PYCALL_PKGID))\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 555, in _call\r\n    self.check_exception(src)\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 609, in check_exception\r\n    raise JuliaError(u'Exception \\'{}\\' occurred while calling julia code:\\n{}'\r\njulia.core.JuliaError: Exception 'InitError' occurred while calling julia code:\r\nconst PyCall = Base.require(Base.PkgId(Base.UUID(\"438e738f-606a-5dbb-bf0a-cddfbfd45ab0\"), \"PyCall\"))\r\n```\r\n\r\nCuriously it works calling the `julia`-library before:\r\n```\r\nPython 3.10.10 (main, Mar 31 2023, 22:33:35) [GCC 8.5.0] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import julia\r\n>>> julia.Julia()\r\n<julia.core.LegacyJulia object at 0x7f7fff0a0550>\r\n>>> import pysr\r\n>>> pysr.install()\r\n```\r\n(I can run the example in this REPL)\r\n\r\nClosing that REPL and trying to run the example again, I arrive at:\r\n```\r\n>>> model.fit(X, y)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/.local/lib/python3.10/site-packages/pysr/sr.py\", line 1834, in fit\r\n    self._run(X, y, mutated_params, weights=weights, seed=seed)\r\n  File \"/home/.local/lib/python3.10/site-packages/pysr/sr.py\", line 1525, in _run\r\n    Main = init_julia(self.julia_project, julia_kwargs=julia_kwargs)\r\n  File \"/home/.local/lib/python3.10/site-packages/pysr/julia_helpers.py\", line 192, in init_julia\r\n    Julia(**julia_kwargs)\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 519, in __init__\r\n    self._call(\"const PyCall = Base.require({0})\".format(PYCALL_PKGID))\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 555, in _call\r\n    self.check_exception(src)\r\n  File \"/home/.local/lib/python3.10/site-packages/julia/core.py\", line 609, in check_exception\r\n    raise JuliaError(u'Exception \\'{}\\' occurred while calling julia code:\\n{}'\r\njulia.core.JuliaError: Exception 'InitError' occurred while calling julia code:\r\nconst PyCall = Base.require(Base.PkgId(Base.UUID(\"438e738f-606a-5dbb-bf0a-cddfbfd45ab0\"), \"PyCall\"))\r\n```\r\n\r\nThis is weird, do you have any idea what could be the problem? Should I raise this with the Pycall-Developers?\r\n\r\n**Version (please include the following information):**\r\n- OS: Linux\r\n- Julia 1.8.5\r\n- Python 3.10.10\r\n- pip-install\r\n- PySR 0.12.1\r\n",
        "comments":
        {
          "nodes":
          [
            {
              "author":
              {
                "login": "MilesCranmer"
              },
              "body": "One thing to try, which is a bit of a hack but might fix it — manually install and build PyCall in the base Julia environment:\r\n\r\n```bash\r\njulia -e 'using Pkg; Pkg.install(\"PyCall\"); Pkg.build(\"PyCall\")'\r\n```\r\n\r\nRun this line in bash in any directory, doesn’t matter which. (Make sure to have the same Python available on your path as if you were using `pysr.install()`)\r\n\r\nThis should add PyCall to the base env which might fix this. Let me know if this works. If not I would then try the solutions in https://github.com/MilesCranmer/PySR/issues/257\r\n\r\nCheers,\r\nMiles",
              "createdAt": "2023-04-01T07:55:19Z"
            },
            {
              "author":
              {
                "login": "dbl001"
              },
              "body": "Perhaps this is the same issue ...\r\nI can run the Feynman problems from iPython  in a terminal, however, I get this error running the code from inside 'Pycharm'\r\n```\r\n\r\n/Users/davidlaxer/anaconda3/envs/pysr_test/bin/python /Users/davidlaxer/PySR/test.py \r\nDEBUG (28160) \r\nDEBUG (28160) Debug-level logging is enabled for PyJulia.\r\nDEBUG (28160) PyJulia version: 0.6.0\r\nDEBUG (28160) \r\n/Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages/julia/juliainfo.py:93: UserWarning: julia warned:\r\nThe latest version of Julia in the `1.9` channel is 1.9.0-rc3+0.x64.apple.darwin14. You currently have `1.9.0-rc2+0.x64.apple.darwin14` installed. Run:\r\n\r\n  juliaup update\r\n\r\nto install Julia 1.9.0-rc3+0.x64.apple.darwin14 and update the `1.9` channel to that version.\r\n  warnings.warn(\"{} warned:\\n{}\".format(julia, stderr))\r\nDEBUG (28160) pyprogramname = None\r\nDEBUG (28160) sys.executable = /Users/davidlaxer/anaconda3/envs/pysr_test/bin/python\r\nDEBUG (28160) bindir = /Users/davidlaxer/.julia/juliaup/julia-1.9.0-rc2+0.x64.apple.darwin14/bin\r\nDEBUG (28160) libjulia_path = /Users/davidlaxer/.julia/juliaup/julia-1.9.0-rc2+0.x64.apple.darwin14/lib/libjulia.1.9.dylib\r\nDEBUG (28160) is_compatible_python = None\r\nDEBUG (28160) use_custom_sysimage = False\r\nDEBUG (28160) compiled_modules = 'no'\r\nDEBUG (28160) argv_list = [b'/Users/davidlaxer/anaconda3/envs/pysr_test/bin/python', b'--compiled-modules=no', b'--threads=auto']\r\nDEBUG (28160) argc = c_int(3)\r\nDEBUG (28160) jl_parse_opts called\r\nDEBUG (28160) argc = c_int(0)\r\nDEBUG (28160) calling jl_init_with_image(/Users/davidlaxer/.julia/juliaup/julia-1.9.0-rc2+0.x64.apple.darwin14/bin, /Users/davidlaxer/.julia/juliaup/julia-1.9.0-rc2+0.x64.apple.darwin14/lib/julia/sys.dylib)\r\nDEBUG (28160) seems to work...\r\n┌ Error: Failed to import PyCall\r\n│   exception =\r\n│    ArgumentError: Package PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] is required but does not seem to be installed:\r\n│     - Run `Pkg.instantiate()` to install all recorded dependencies.\r\n│    \r\n│    Stacktrace:\r\n│     [1] _require(pkg::Base.PkgId, env::Nothing)\r\n│       @ Base ./loading.jl:1741\r\n│     [2] _require_prelocked(uuidkey::Base.PkgId, env::Nothing)\r\n│       @ Base ./loading.jl:1623\r\n│     [3] _require_prelocked\r\n│       @ ./loading.jl:1621 [inlined]\r\n│     [4] macro expansion\r\n│       @ ./lock.jl:267 [inlined]\r\n│     [5] require(uuidkey::Base.PkgId)\r\n│       @ Base ./loading.jl:1618\r\n│     [6] top-level scope\r\n│       @ none:3\r\n└ @ Main none:5\r\nDEBUG (28160) exception occured? 5841618960\r\nTraceback (most recent call last):\r\n  File \"/Users/davidlaxer/PySR/test.py\", line 11, in <module>\r\n    julia = Julia(compiled_modules=False, debug=True, threads='auto')\r\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages/julia/core.py\", line 702, in __init__\r\n    self.__julia = Julia(*args, **kwargs)\r\n                   ^^^^^^^^^^^^^^^^^^^^^^\r\n  File \"/Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages/julia/core.py\", line 510, in __init__\r\n    self._call(\"\"\"\r\n  File \"/Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages/julia/core.py\", line 555, in _call\r\n    self.check_exception(src)\r\n  File \"/Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages/julia/core.py\", line 609, in check_exception\r\n    raise JuliaError(u'Exception \\'{}\\' occurred while calling julia code:\\n{}'\r\njulia.core.JuliaError: Exception 'ArgumentError' occurred while calling julia code:\r\n\r\n            const PyCall = try\r\n                Base.require(Base.PkgId(Base.UUID(\"438e738f-606a-5dbb-bf0a-cddfbfd45ab0\"), \"PyCall\"))\r\n            catch err\r\n                @error \"Failed to import PyCall\" exception = (err, catch_backtrace())\r\n                rethrow()\r\n            end\r\n            \r\n\r\nSYSTEM: caught exception of type :ArgumentError while trying to print a failed Task notice; giving up\r\n\r\nProcess finished with exit code 1\r\n\r\n```\r\nHere's the test script:\r\n```\r\nimport os\r\n\r\n# Set the number of threads for Julia\r\nos.environ[\"JULIA_NUM_THREADS\"] = \"4\"\r\n\r\nimport pysr\r\n\r\nfrom julia import Julia\r\njulia = Julia(compiled_modules=False, debug=True, threads='auto')\r\n\r\nfrom julia import Main\r\nfrom julia.tools import redirect_output_streams\r\n\r\n#redirect_output_streams()\r\n\r\npysr.install()\r\n\r\nfrom pysr.sr import pysr, best\r\nfrom pysr.feynman_problems import FeynmanProblem\r\nfrom pysr.feynman_problems import mk_problems\r\nfrom pysr.feynman_problems import run_on_problem\r\nfrom pysr.feynman_problems import do_feynman_experiments\r\nfrom pysr.feynman_problems import do_feynman_experiments_parallel\r\n\r\n\r\nimport sympy\r\nfrom sympy.core.random import _randint\r\nimport numpy as np\r\nfrom matplotlib import pyplot as plt\r\nfrom pysr import PySRRegressor\r\nimport torch\r\nfrom torch import nn, optim\r\nfrom torch.nn import functional as F\r\nfrom torch.utils.data import DataLoader, TensorDataset\r\nimport pytorch_lightning as pl\r\nfrom sklearn.model_selection import train_test_split\r\n\r\n\r\ndo_feynman_experiments()\r\n\r\n```\r\nEnvironment:\r\n```\r\n% julia\r\n               _\r\n   _       _ _(_)_     |  Documentation: https://docs.julialang.org\r\n  (_)     | (_) (_)    |\r\n   _ _   _| |_  __ _   |  Type \"?\" for help, \"]?\" for Pkg help.\r\n  | | | | | | |/ _` |  |\r\n  | | |_| | | | (_| |  |  Version 1.9.0-rc3 (2023-04-26)\r\n _/ |\\__'_|_|_|\\__'_|  |  Official https://julialang.org/ release\r\n|__/                   |\r\n\r\njulia> using Pkg\r\n\r\njulia> Pkg.add(\"PyCall\")\r\n   Resolving package versions...\r\n  No Changes to `~/anaconda3/envs/pysr_test/share/julia/environments/pysr_test/Project.toml`\r\n  No Changes to `~/anaconda3/envs/pysr_test/share/julia/environments/pysr_test/Manifest.toml`\r\n\r\njulia> Pkg.update(\"PyCall\")\r\n  No Changes to `~/anaconda3/envs/pysr_test/share/julia/environments/pysr_test/Project.toml`\r\n  No Changes to `~/anaconda3/envs/pysr_test/share/julia/environments/pysr_test/Manifest.toml`\r\n\r\njulia> \r\n(pysr_test) davidlaxer@bluediamond julia % ipython          \r\nPython 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:51) [Clang 14.0.4 ]\r\nType 'copyright', 'credits' or 'license' for more information\r\nIPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.\r\n\r\nIn [1]: from julia.api import JuliaInfo\r\n\r\nIn [2]: info = JuliaInfo.load()\r\n\r\nIn [3]: info.is_compatible_python()\r\nOut[3]: False\r\n\r\nIn [4]: info.python\r\nOut[4]: '/Users/davidlaxer/anaconda3/envs/pysr_test/bin/python'\r\n\r\nIn [5]: info.sysimage\r\nOut[5]: '/Users/davidlaxer/anaconda3/envs/pysr_test/share/julia/juliaup/julia-1.9.0-rc3+0.x64.apple.darwin14/lib/julia/sys.dylib'\r\n\r\n```\r\n\r\n<img width=\"1404\" alt=\"Screenshot 2023-05-07 at 10 39 11 AM\" src=\"https://user-images.githubusercontent.com/3105499/236693553-b0d909b2-581f-4260-aeb1-ba7fbc532075.png\">\r\n",
              "createdAt": "2023-05-07T17:40:09Z"
            },
            {
              "author":
              {
                "login": "dbl001"
              },
              "body": "In my environment, PyCharm was invoking julia in:\r\n```\r\n/Users/davidlaxer/.julia/juliaup/julia-1.9.0+0.x64.apple.darwin14/bin/julia\r\n```\r\ninstead of from my conda virtual environment:\r\n```\r\n/Users/davidlaxer/anaconda3/envs/pysr_test//bin/julia\r\n```\r\nThe julia environment in: /Users/davidlaxer/.julia/juliaup/julia-1.9.0+0.x64.apple.darwin14/bin/julia did not have 'pycall' installed.",
              "createdAt": "2023-05-20T02:51:42Z"
            },
            {
              "author":
              {
                "login": "MilesCranmer"
              },
              "body": "Hm, this might be a different issue. Did you install PySR with pip instead of conda?",
              "createdAt": "2023-05-20T12:16:00Z"
            },
            {
              "author":
              {
                "login": "dbl001"
              },
              "body": "Look like: $ python setup.py develop\r\n\r\n```\r\n% conda list pysr\r\n# packages in environment at /Users/davidlaxer/anaconda3/envs/pysr_test:\r\n#\r\n# Name                    Version                   Build  Channel\r\npysr                      0.12.3                    dev_0    <develop>\r\n(pysr_test) davidlaxer@bluediamond julia % pip show pysr\r\nName: pysr\r\nVersion: 0.11.11\r\nSummary: Simple and efficient symbolic regression\r\nHome-page: https://github.com/MilesCranmer/pysr\r\nAuthor: Miles Cranmer\r\nAuthor-email: miles.cranmer@gmail.com\r\nLicense: \r\nLocation: /Users/davidlaxer/anaconda3/envs/pysr_test/lib/python3.11/site-packages\r\nRequires: julia, numpy, pandas, scikit-learn, sympy\r\nRequired-by: \r\n\r\n```",
              "createdAt": "2023-05-20T13:39:40Z"
            },
            {
              "author":
              {
                "login": "MilesCranmer"
              },
              "body": "Okay I think that's a different issue. If using conda's Julia then you likely would also need to use conda's PySR (https://github.com/conda-forge/pysr-feedstock) so it gets the paths correctly.",
              "createdAt": "2023-05-20T14:50:57Z"
            },
            {
              "author":
              {
                "login": "MilesCranmer"
              },
              "body": "Presumably fixed by #535, so closing.",
              "createdAt": "2024-02-12T09:02:37Z"
            }
          ],
          "pageInfo":
          {
            "hasNextPage": false,
            "endCursor": "Y3Vyc29yOnYyOpHOc4enQw=="
          }
        }
      }
    }
  }
}